const adminRoutes = [
  {
    name: 'dashboard',
    icon: 'dashboard',
    url: 'dashboard',
    id: 'dashboard',
  },
  {
    name: 'location',
    id: 'deliveryzone_management',
    icon: 'deliveryzone',
    submenu: [
      {
        name: 'region',
        icon: 'delivery',
        id: 'region',
        url: 'deliveryzone/region',
        children: [],
      },
      {
        name: 'country',
        icon: 'delivery',
        id: 'country',
        url: 'deliveryzone/country',
        children: [],
      },
      {
        name: 'city',
        icon: 'delivery',
        id: 'city',
        url: 'deliveryzone/city',
        children: [],
      },
      {
        name: 'area',
        icon: 'delivery',
        id: 'area',
        url: 'deliveryzone/area',
        children: [],
      },
    ],
  },
  // {
  //   name: 'vacancy',
  //   id: 'vacancy_management',
  //   icon: 'branches',
  //   submenu: [
  //     {
  //       name: 'vacancies',
  //       icon: 'dropbox',
  //       url: 'vacancies',
  //       id: 'vacancies',
  //       children: [],
  //     },
  //     {
  //       name: 'vacancy.categories',
  //       icon: 'appStore',
  //       url: 'catalog/vacancyCategories',
  //       id: 'vacancy_categories',
  //       children: [],
  //     },
  //   ],
  // },
  {
    name: 'product',
    id: 'product_management',
    icon: 'branches',
    submenu: [
      {
        name: 'products',
        icon: 'dropbox',
        url: 'products',
        id: 'products',
        children: [],
      },
      {
        name: 'categories',
        icon: 'appStore',
        url: 'catalog/categories',
        id: 'categories',
        children: [],
      },
      {
        name: 'attributes',
        icon: 'ControlOutlined',
        url: 'attributes',
        id: 'attributes',
        children: [],
      },
    ],
  },
  {
    name: 'content',
    id: 'content_management',
    icon: 'appStoreAdd',
    submenu: [
      // {
      //   name: 'brands',
      //   icon: 'appStoreAdd',
      //   url: 'catalog/brands',
      //   id: 'brands',
      //   children: [],
      // },
      // {
      //   name: 'career',
      //   icon: 'CaretUpOutlined',
      //   url: 'careers/list',
      //   id: 'career_sub_management',
      //   children: [
      //     {
      //       name: 'career',
      //       icon: 'caretUp',
      //       url: 'catalog/career',
      //       id: 'catalog_career',
      //       children: [],
      //     },
      //     {
      //       name: 'career.categories',
      //       icon: 'careerCategory',
      //       url: 'catalog/career-categories',
      //       id: 'career_categories',
      //       children: [],
      //     },
      //   ],
      // },
      // {
      //   name: 'units',
      //   icon: 'disconnect',
      //   url: 'catalog/units',
      //   id: 'units',
      //   children: [],
      // },
      // {
      //   name: 'banners',
      //   icon: 'bsImage',
      //   url: 'banners',
      //   id: 'banners',
      //   children: [],
      // },
      {
        name: 'blogs',
        url: 'blogs',
        icon: 'form',
        id: 'blogs',
        children: [],
      },
      {
        name: 'stories',
        icon: 'BsClockHistory',
        url: 'stories',
        id: 'stories',
        children: [],
      },
      {
        name: 'gallery',
        url: 'gallery',
        icon: 'fiImage',
        id: 'gallery',
        children: [],
      },
      {
        name: 'notifications',
        icon: 'notificationsActive',
        url: 'notifications',
        id: 'notifications',
        children: [],
      },
    ],
  },
  {
    name: 'ads',
    id: 'advert_management',
    icon: 'appStoreAdd',
    submenu: [
      {
        name: 'ads',
        id: 'ads',
        url: 'catalog/advert',
        icon: 'appStore',
      },
    ],
  },
  {
    name: 'users',
    icon: 'user',
    url: 'users',
    id: 'user_management',
    submenu: [
      // {
      //   name: 'clients',
      //   icon: 'user',
      //   url: 'users/user',
      //   id: 'clients',
      // },
      {
        name: 'users',
        icon: 'userGroupAdd',
        url: 'users/admin',
        id: 'users',
      },
      {
        name: 'roles',
        icon: 'userSwitch',
        url: 'users/role',
        id: 'roles',
      },
      {
        name: 'referral',
        icon: 'referral',
        url: 'settings/referal',
        id: 'referral',
        children: [],
      },
    ],
  },
  {
    name: 'money',
    id: 'money_management',
    icon: 'wallet',
    submenu: [
      {
        name: 'wallets',
        icon: 'wallet',
        url: 'wallets',
        id: 'wallets',
        children: [],
      },
      {
        name: 'transactions',
        icon: 'transaction',
        url: 'transactions',
        id: 'transactions',
        children: [],
      },
      {
        name: 'email.subscriber',
        icon: 'mail',
        url: 'email/subscriber',
        id: 'email_subscriber_sub_management',
        children: [
          {
            name: 'subscriber',
            icon: 'MdNotificationAdd',
            url: 'subscriber',
            id: 'subscriber',
          },
          {
            name: 'message.subscriber',
            icon: 'MdNotificationAdd',
            url: 'message/subscriber',
            id: 'message_subscriber',
          },
        ],
      },
    ],
  },
  {
    name: 'statistics',
    id: 'statistics_management',
    icon: 'chart-line',
    submenu: [
      {
        name: 'products',
        icon: 'products',
        url: 'report/products',
        id: 'report_products',
        children: [],
      },
      {
        name: 'users',
        icon: 'user',
        url: 'report/users',
        id: 'report_users',
        children: [],
      },
    ],
  },
  {
    name: 'business.settings',
    id: 'business_settings_management',
    icon: 'settings',
    submenu: [
      {
        name: 'settings.general',
        icon: 'settings',
        url: 'settings/general',
        id: 'settings_general',
        children: [],
      },
      {
        name: 'currencies',
        icon: 'moneyCollect',
        url: 'currencies',
        id: 'currencies',
        children: [],
      },
      {
        name: 'payments',
        icon: 'wallet',
        url: 'settings/payments',
        id: 'payments',
        children: [],
      },
      {
        name: 'payment.payloads',
        icon: 'payload',
        url: 'payment-payloads',
        id: 'payment_payloads',
        children: [],
      },
      {
        name: 'sms-payload',
        icon: 'message',
        url: 'settings/sms-payload',
        id: 'sms-payload',
        children: [],
      },
      {
        name: 'email.provider',
        icon: 'emailSettings',
        url: 'settings/emailProviders',
        id: 'email_provider',
        children: [],
      },
      {
        name: 'notification.settings',
        icon: 'notificationsActive',
        url: 'settings/firebase',
        id: 'notification_settings',
        children: [],
      },
      {
        name: 'social.settings',
        icon: 'instagram',
        url: 'settings/social',
        id: 'social_settings',
        children: [],
      },
      {
        name: 'app.settings',
        icon: 'GrAppleAppStore',
        url: 'settings/app',
        id: 'app_settings',
        children: [],
      },
    ],
  },
  {
    name: 'system.settings',
    id: 'system_settings_management',
    icon: 'global',
    submenu: [
      {
        name: 'languages',
        icon: 'global',
        url: 'settings/languages',
        id: 'languages',
        children: [],
      },
      {
        name: 'translations',
        icon: 'translation',
        url: 'settings/translations',
        id: 'translations',
        children: [],
      },
      {
        icon: 'database',
        url: 'settings/backup',
        name: 'backup',
        id: 'backup',
        children: [],
      },
      {
        name: 'system.information',
        icon: 'tool',
        url: 'settings/system-information',
        id: 'system_information',
        children: [],
      },
      {
        name: 'update',
        icon: 'cloudUpload',
        url: 'settings/update',
        id: 'update',
        children: [],
      },
      {
        name: 'clear.cash',
        icon: 'AiOutlineClear',
        url: 'settings/cashClear',
        id: 'clear_cash',
        children: [],
      },
    ],
  },
  // {
  //   name: 'page.setup',
  //   icon: 'settings',
  //   url: 'settings',
  //   id: 'page_setup_management',
  //   submenu: [
  //     {
  //       name: 'faq',
  //       icon: 'questionCircle',
  //       url: 'settings/faqs',
  //       id: 'faq',
  //     },
  //     {
  //       name: 'terms',
  //       icon: 'paperClip',
  //       url: 'settings/terms',
  //       id: 'terms',
  //     },
  //     {
  //       name: 'policy',
  //       icon: 'lock',
  //       url: 'settings/policy',
  //       id: 'policy',
  //     },
  //     {
  //       name: 'pages',
  //       icon: 'RiPageSeparator',
  //       url: 'pages',
  //       id: 'pages',
  //     },
  //     {
  //       name: 'landing.page',
  //       icon: 'FileTextOutlined',
  //       url: 'settings/landing-page',
  //       id: 'landing_page',
  //     },
  //   ],
  // },
  {
    name: 'logout',
    icon: 'logout',
    url: '',
    id: 'logout',
  },
];

const managerRoutes = [
  {
    name: 'dashboard',
    icon: 'dashboard',
    url: 'dashboard',
    id: 'dashboard_1',
  },
  {
    name: 'product',
    id: 'product_management_1',
    icon: 'branches',
    submenu: [
      {
        name: 'products',
        icon: 'dropbox',
        url: 'products',
        id: 'products_1',
        children: [],
      },
      {
        name: 'categories',
        icon: 'appStore',
        url: 'catalog/categories',
        id: 'categories_1',
        children: [],
      },
      {
        name: 'attributes',
        icon: 'ControlOutlined',
        url: 'attributes',
        id: 'attributes_1',
        children: [],
      },
    ],
  },
  {
    name: 'content',
    id: 'content_management_1',
    icon: 'appStoreAdd',
    submenu: [
      // {
      //   name: 'brands',
      //   icon: 'appStoreAdd',
      //   url: 'catalog/brands',
      //   id: 'brands_1',
      //   children: [],
      // },
      {
        name: 'blogs',
        url: 'blogs',
        icon: 'form',
        id: 'blogs_1',
        children: [],
      },
      {
        name: 'stories',
        icon: 'BsClockHistory',
        url: 'stories',
        id: 'stories_1',
        children: [],
      },
      {
        name: 'gallery',
        url: 'gallery',
        icon: 'fiImage',
        id: 'gallery_1',
        children: [],
      },
      {
        name: 'notifications',
        icon: 'notificationsActive',
        url: 'notifications',
        id: 'notifications_1',
        children: [],
      },
    ],
  },
  {
    name: 'ads',
    id: 'advert_management_1',
    icon: 'appStoreAdd',
    submenu: [
      {
        name: 'ads',
        id: 'ads_1',
        url: 'catalog/advert',
        icon: 'appStore',
      },
    ],
  },
  {
    name: 'users',
    icon: 'user',
    url: 'users',
    id: 'user_management_1',
    submenu: [
      {
        name: 'users',
        icon: 'userGroupAdd',
        url: 'users/admin',
        id: 'users_1',
      },
      {
        name: 'roles',
        icon: 'userSwitch',
        url: 'users/role',
        id: 'roles_1',
      },
      {
        name: 'referral',
        icon: 'referral',
        url: 'settings/referal',
        id: 'referral_1',
        children: [],
      },
    ],
  },
  {
    name: 'money',
    id: 'money_management_1',
    icon: 'wallet',
    submenu: [
      {
        name: 'wallets',
        icon: 'wallet',
        url: 'wallets',
        id: 'wallets_1',
        children: [],
      },
      {
        name: 'transactions',
        icon: 'transaction',
        url: 'transactions',
        id: 'transactions_1',
        children: [],
      },
      {
        name: 'email.subscriber',
        icon: 'mail',
        url: 'email/subscriber',
        id: 'email_subscriber_sub_management_1',
        children: [
          {
            name: 'subscriber',
            icon: 'MdNotificationAdd',
            url: 'subscriber',
            id: 'subscriber_1',
          },
          {
            name: 'message.subscriber',
            icon: 'MdNotificationAdd',
            url: 'message/subscriber',
            id: 'message_subscriber_1',
          },
        ],
      },
    ],
  },
  {
    name: 'statistics',
    id: 'statistics_management_1',
    icon: 'chart-line',
    submenu: [
      {
        name: 'products',
        icon: 'products',
        url: 'report/products',
        id: 'report_products_1',
        children: [],
      },
      {
        name: 'users',
        icon: 'user',
        url: 'report/users',
        id: 'report_users_1',
        children: [],
      },
    ],
  },
  {
    name: 'business.settings',
    id: 'business_settings_management_1',
    icon: 'settings',
    submenu: [
      {
        name: 'settings.general',
        icon: 'settings',
        url: 'settings/general',
        id: 'settings_general_1',
        children: [],
      },
      {
        name: 'currencies',
        icon: 'moneyCollect',
        url: 'currencies',
        id: 'currencies_1',
        children: [],
      },
      {
        name: 'payments',
        icon: 'wallet',
        url: 'settings/payments',
        id: 'payments_1',
        children: [],
      },
      {
        name: 'payment.payloads',
        icon: 'payload',
        url: 'payment-payloads',
        id: 'payment_payloads_1',
        children: [],
      },
      {
        name: 'sms-payload',
        icon: 'message',
        url: 'settings/sms-payload',
        id: 'sms-payload_1',
        children: [],
      },
      {
        name: 'email.provider',
        icon: 'emailSettings',
        url: 'settings/emailProviders',
        id: 'email_provider_1',
        children: [],
      },
      {
        name: 'notification.settings',
        icon: 'notificationsActive',
        url: 'settings/firebase',
        id: 'notification_settings_1',
        children: [],
      },
      {
        name: 'social.settings',
        icon: 'instagram',
        url: 'settings/social',
        id: 'social_settings_1',
        children: [],
      },
      {
        name: 'app.settings',
        icon: 'GrAppleAppStore',
        url: 'settings/app',
        id: 'app_settings_1',
        children: [],
      },
    ],
  },
  {
    name: 'system.settings',
    id: 'system_settings_management_1',
    icon: 'global',
    submenu: [
      {
        name: 'languages',
        icon: 'global',
        url: 'settings/languages',
        id: 'languages_1',
        children: [],
      },
      {
        name: 'translations',
        icon: 'translation',
        url: 'settings/translations',
        id: 'translations_1',
        children: [],
      },
      {
        icon: 'database',
        url: 'settings/backup',
        name: 'backup',
        id: 'backup_1',
        children: [],
      },
      {
        name: 'system.information',
        icon: 'tool',
        url: 'settings/system-information',
        id: 'system_information_1',
        children: [],
      },
      {
        name: 'update',
        icon: 'cloudUpload',
        url: 'settings/update',
        id: 'update_1',
        children: [],
      },
      {
        name: 'clear.cash',
        icon: 'AiOutlineClear',
        url: 'settings/cashClear',
        id: 'clear_cash_1',
        children: [],
      },
    ],
  },
  {
    name: 'logout',
    icon: 'logout',
    url: '',
    id: 'logout_1',
  },
];

export const data = {
  admin: adminRoutes,
  manager: managerRoutes,
};
