name: quick
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_facebook_auth: ^5.0.11  # Comment this line

  # Windows specific dependencies
  # flutter_secure_storage_windows: ^3.0.0  # Changed from ^4.0.0 to ^3.0.0
  # window_manager: ^0.4.3
  # bitsdojo_window: ^0.1.6

  #base:
  dio: any
  intl: any
  http: any
  bloc: any
  get_it: any
  collection: any
  google_fonts: any
  shared_preferences: any
  flutter_screenutil: any
  freezed_annotation: ^3.0.0  # Changed to match flutter_gemini requirements
  ftoast: ^2.0.0
  dartz: ^0.10.1
  freezed: ^3.0.6  # Changed to match freezed_annotation
  provider: ^6.1.2
  share_plus: ^10.1.1
  flutter_bloc: ^9.1.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.3
  flutter_isolate: ^2.1.0
  webview_flutter: ^4.10.0
  connectivity_plus: ^6.0.5
  flutter_displaymode: ^0.6.0
  permission_handler: ^12.0.0+1
  dropdown_button2: ^2.3.9
  upgrader: ^11.3.0
  flutter_gemini: ^3.0.0
  loading_animation_widget: ^1.2.1

  #ui
  jiffy: ^6.3.1
  chewie: ^1.8.1
  lottie: ^3.1.2
  readmore: ^3.0.0
  swipe_to: ^1.0.6
  remixicon: ^1.3.0
  flutter_svg: ^2.0.16
  grouped_list: ^6.0.0
  sms_autofill: ^2.4.1
  measure_size: ^4.0.0
  dotted_border: ^2.1.0
  auto_size_text: ^3.0.0
  pull_to_refresh: ^2.0.0
  carousel_slider: ^5.0.0
  flutter_slidable: ^4.0.0
  phone_text_field: ^0.0.6
  flutter_rating_bar: ^4.0.1
  zoom_pinch_overlay: ^1.4.3
  flutter_html: ^3.0.0-beta.2
  proste_indexed_stack: ^0.2.4
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.4.3
  flutter_swipe_detector: ^2.0.0
  flutter_advanced_switch: ^3.1.0
  flutter_keyboard_visibility: ^6.0.0
  rotated_corner_decoration: ^2.1.0+1
  flutter_staggered_grid_view: ^0.7.0

  #media:
  image: any
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  video_player: ^2.9.2
  cached_network_image: ^3.2.0
  flutter_sound: ^9.2.13
  just_audio: ^0.9.34

  #maps:
  geolocator: ^14.0.0
  osm_nominatim: ^3.0.1
  google_maps_flutter: ^2.12.1

  #firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_messaging: ^15.2.5
  firebase_storage: ^12.4.5
  # firebase_dynamic_links: ^5.5.7  # Removed as discontinued
  # package_info_plus: ^8.3.0  # Disabled due to Kotlin compilation issues

  #sign_in:
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^7.0.1
  # flutter_facebook_auth: ^6.1.0
  app_tracking_transparency: ^2.0.6

  #patients


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/app_logo.png'
  adaptive_icon_foreground: 'assets/images/app_logo.png'
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  background_image: 'assets/images/splash.png'
  android_12:
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/

