///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesAppLogo = 'assets/images/app_logo.png';
  static const String imagesBackground = 'assets/images/background.png';
  static const String imagesDarkBg = 'assets/images/darkBg.jpeg';
  static const String imagesEmptyCart = 'assets/images/emptyCart.png';
  static const String imagesHelpBack = 'assets/images/help_back.png';
  static const String imagesLightBg = 'assets/images/lightBg.jpeg';
  static const String imagesNoLike = 'assets/images/no_like.png';
  static const String imagesOrderSuccess = 'assets/images/order_success.png';
  static const String imagesPaymentRejected = 'assets/images/payment_rejected.png';
  static const String imagesSplash = 'assets/images/splash.png';
  static const String lottieEmptyList = 'assets/lottie/empty_list.json';
  static const String lottieEmptyReview = 'assets/lottie/empty_review.json';
  static const String lottieNoImage = 'assets/lottie/noImage.json';
  static const String lottieNoItem = 'assets/lottie/noItem.json';
  static const String lottieNotificationEmpty = 'assets/lottie/notification_empty.json';
  static const String lottieOrderNot = 'assets/lottie/order_not.json';
  static const String lottiePin = 'assets/lottie/pin.json';
  static const String lottieProcessing = 'assets/lottie/processing.json';
  static const String svgBag = 'assets/svg/bag.svg';
  static const String svgCategory = 'assets/svg/category.svg';
  static const String svgContact = 'assets/svg/contact.svg';
  static const String svgDiscount = 'assets/svg/discount.svg';
  static const String svgFilter = 'assets/svg/filter.svg';
  static const String svgHome = 'assets/svg/home.svg';
  static const String svgInStock = 'assets/svg/inStock.svg';
  static const String svgLike = 'assets/svg/like.svg';
  static const String svgMenu = 'assets/svg/menu.svg';
  static const String svgOutOfStock = 'assets/svg/outOfStock.svg';
  static const String svgSelectBag = 'assets/svg/selectBag.svg';
  static const String svgSelectHome = 'assets/svg/selectHome.svg';
  static const String svgSelectLike = 'assets/svg/selectLike.svg';
  static const String svgSelectMenu = 'assets/svg/selectMenu.svg';
  static const String svgStart = 'assets/svg/start.svg';

}
